FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    emacs-nox \
    wget \
    sudo \
    git \
    libtool \
    automake \
    autoconf \
    gdb \
    strace \
    python3
