name: github-docker-test

on:
  push:
    branches: [sarich/github-docker-test]
  pull_request:
    branches: [sarich/github-docker-test]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: test
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }}
